### ISSUE TITLE
Drag Scrolling in Mobile

### ISSUE THREAD

**Issue by Geoff-Fernandez** [rfmiotto/react-use-draggable-scroll#23]
Hello,

Does this hook also supports mobile? If so, how could I enable it?

Thanks in advance.

**Comment by bramchi** [comment]
I've used this CSS to restore horizontal scrolling on mobile when using this package:

```CSS
overflow-x: hidden;
  
@media (hover: none) {
  overflow-x: auto;
}
```

It prevents overflowing by default so `react-use-draggable-scroll` can do its thing, but for touch devices it allows regular scrollable overflowing.

Not sure if it's the recommended way, but it does the trick for me.
